### ISSUE TITLE
콘솔창에 띄우는 명령어는 무엇이 좋을까요

### ISSUE THREAD

**Issue by milkycyj** [st-cpp-project/getrich#3]
현욱이가 말하길 cout 은 코스트가 많이 든다고 합니다

cout
printf
cprintf (conio.h)
_cputs (conio.h)

그 외에도 뭐가 효율적일지 알려주시면 감사하겠습니다

**Comment by Quirax** [comment]
만약에 굳이 형식(template)을 사용할 일이 없다면 cputs를 쓰는 게 가장 효율적입니다. 말 그대로 주는 대로 뿌려주거든요.
만약 형식을 쓴다면 cout을 쓰거나 printf를 쓰는 게 좋을텐데, 아마 코드 가독성 때문에라도 printf를 쓰는 게 좋을 거라고 생각합니다.
If you don't need to use template, cputs is most efficient, because it prints what you give.
If you need to use template, you may use cout or printf. But I think using printf is prefer because of readability of code.

**Comment by KUvH** [comment]
추가적으로 http://egloos.zum.com/minjang/v/1934885 이 글을 읽어보는 것도 괜찮을 것 같습니다.

**Comment by milkycyj** [comment]
cputs는 유니코드를 지원하지 않는다네요
그래서 주사위의 특수기호를 출력할 때 글씨가 깨집니다

**Comment by Quirax** [comment]
일단 공식적으로 출력 함수들은 유니코드를 지원하지 않습니다. 근데 혹시 주사위의 특수기호가 출력되는 부분만 올려주시겠습니까?

Officially, output functions does not support unicode.
By the way, would you like to upload the part where the special character of dice is printed?

**Comment by milkycyj** [comment]
![sdg](https://cloud.githubusercontent.com/assets/22634992/20602443/8af1960c-b2a0-11e6-89e7-2c20feb84ef7.png)

앗 그렇군요
콘솔에서 이렇게 깨집니다

그리고 코드입니다

	void Dice::showDice(int point){
		switch (point){
		case 1:
			_cputs("┌───┐\n");
			_cputs("│　　　│\n");
			_cputs("│　○　│\n");
			_cputs("│　　　│\n");
			_cputs("└───┘\n");
			break;
		case 2:
			_cputs("┌───┐\n");
			_cputs("│○　　│\n");
			_cputs("│　　　│\n");
			_cputs("│　　○│\n");
			_cputs("└───┘\n");
			break;
		case 3:
			_cputs("┌───┐\n");
			_cputs("│○　　│\n");
			_cputs("│　○　│\n");
			_cputs("│　　○│\n");
			_cputs("└───┘\n");
			break;
		case 4:
			_cputs("┌───┐\n");
			_cputs("│○　○│\n");
			_cputs("│　　　│\n");
			_cputs("│○　○│\n");
			_cputs("└───┘\n");
			break;
		case 5:
			_cputs("┌───┐\n");
			_cputs("│○　○│\n");
			_cputs("│　○　│\n");
			_cputs("│○　○│\n");
			_cputs("└───┘\n");
			break;
		case 6:
			_cputs("┌───┐\n");
			_cputs("│○○○│\n");
			_cputs("│　　　│\n");
			_cputs("│○○○│\n");
			_cputs("└───┘\n");
			break;
		}
	}

**Comment by milkycyj** [comment]
github 상에서 소스 보기로 해도 특수문자가 죄다 깨지는군요

**Comment by Quirax** [comment]
일단 레퍼런스에서는 _cputws 함수를 사용하라고 하네요.

**Comment by KUvH** [comment]
printf를 사용하는 것이 잠정적으로 결정되었습니다.
