### ISSUE TITLE
커서 이동과 관련하여 레퍼런스 자료 물어다 놓습니다

### ISSUE THREAD

**Issue by Quirax** [st-cpp-project/getrich#4]
ANSI 이스케이프 문자를 이용하여 커서 이동이 가능하다고 합니다.
일단 실험이 필요하겠지만 유용할 것 같습니다.

**Reference on cursor movement**
It says that we can move cursor using ANSI escape sequences.
We need some experiments on this, but perhaps it will be useful.

http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html

**Comment by KUvH** [comment]
윈도우에서 호환성 문제가 있지 않을까요?
http://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences
https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx
일단 자료 몇개를 좀 더 수집했습니다.
참고 하시기 바랍니다.

**Comment by Quirax** [comment]
일단 Windows 10에서 동작하는 것은 확인했으나, 만약 하위 버전 호환성을 고려한다면 화면 전체를 리프레시하는 게 최선이겠네요.
I have ever confirmed that it works on Windows 10, but if you think about compatibility of older version, it is prefer to refresh entire screen.

**Comment by KUvH** [comment]
Windows.h 에 있는 콘솔 관련 함수를 사용하면 커서 이동 및 텍스트 출력시 background와 foreground 색상을 지정하여 출력할 수 있습니다. 나중에 ConsoleView를 master 브랜치로 병합할 예정입니다.

**Comment by KUvH** [comment]
#245c7177d222aa34af114cd452be532685e47474
