### ISSUE TITLE
CP949과 기타등의 인코딩으로 인해 Windows가 아닌 환경에서 문자가 깨진 상태로 저장되는 현상 발생

### ISSUE THREAD

**Issue by KUvH** [st-cpp-project/getrich#8]
Windows에서 작업한 소스를 Mac에서 저장하여 git에 푸시하고 다시 받아서 Windows에서 보면
글자가 깨진 상태가 되어버리는 문제가 발생하였습니다.

나중에 컴파일 할 때에도 문제가 발생하기 때문에 인코딩 문제를 현재 해결 중 입니다....

**Comment by Quirax** [comment]
우선 제쪽에서도 설정파일을 변경해서 해결해보겠습니다. 불편을 드려 죄송합니다.

**Comment by KUvH** [comment]
UTF-8 (BOM) 형식으로 모든 파일을 인코딩 하였습니다.
왠만한 환경에서는 더이상 깨지지 않겠지만, 다시 발생할 경우 다시 이슈를 열어주시기 바랍니다.
